name: puch deps

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      run: git clone https://github.com/AndroidIDE-CN/AIDE-Plus
    - name: lsd
      run: ls 
